# Generated by Django 2.1.4 on 2019-12-26 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20191226_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='group',
            field=models.CharField(max_length=128),
        ),
    ]
